config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root "main#home"

  resources :categories, only: [:index, :show]
  resources :labours, except: :show
  resources :areas, only: :index
  resources :skills

  resources :clients do
    put :assign_user, on: :member
  end

  resources :users

  resources :technicians do
    put :add_skill, on: :member
    delete :delete_skill, on: :member

    put :add_labour, on: :member
    delete :delete_labour, on: :member
  end

  resources :services do
      put :add_labour, on: :member
      delete :delete_labour, on: :member
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!

  def home
    # @root_categories = Category.areas
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/home.html.erb
<div class="row justify-content-center mt-6">
  <div class="col-md-6 mb-4">
    <div class="card text-center border-info">
      <div class="card-body">
        <h1><%= link_to 'Categorias'.upcase, categories_path %></h1>
      </div>
    </div>
  </div>

  <% if current_user.admin? %> 
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Usuarios'.upcase, users_path %></h1>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.technician? || current_user.admin? %>
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Labores'.upcase, labours_path %></h1>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Tecnicos'.upcase, technicians_path %></h1>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.admin? || current_user.technician?  %>
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Habilidades'.upcase, skills_path %></h1>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Clientes'.upcase, clients_path %></h1>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user.admin? || current_user.client? %>
    <div class="col-md-6 mb-4">
      <div class="card text-center border-info">
        <div class="card-body">
          <h1><%= link_to 'Servicios'.upcase, services_path %></h1>
        </div>
      </div>
    </div>
  <% end %>
</div>