config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root "main#home"

  resources :categories, only: [:index, :show]
  resources :labours, except: :show
  resources :areas, only: :index
  resources :skills

  resources :clients do
    put :assign_user, on: :member
  end

  resources :users

  resources :technicians do
    put :add_skill, on: :member
    delete :delete_skill, on: :member

    put :add_labour, on: :member
    delete :delete_labour, on: :member
  end

  resources :services do
      put :add_labour, on: :member
      delete :delete_labour, on: :member
  end
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id            :integer          not null, primary key
#  description   :string
#  end_date      :datetime
#  initial_date  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  client_id     :integer          not null
#  technician_id :integer          not null
#
# Indexes
#
#  index_services_on_client_id      (client_id)
#  index_services_on_technician_id  (technician_id)
#
# Foreign Keys
#
#  client_id      (client_id => clients.id)
#  technician_id  (technician_id => technicians.id)
#
class Service < ApplicationRecord
  belongs_to :client
  belongs_to :technician

  has_many :service_labours, dependent: :destroy
  has_many :labours, through: :service_labours

  validates_presence_of :client_id, :technician_id, :description, :initial_date
  validate :end_date_after_initial_date

  private

  def end_date_after_initial_date
    return unless initial_date.present? && end_date.present?

    errors.add(:end_date, 'must be after the initial date') if end_date < initial_date
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :authorize_client
	before_action :set_service, only: [:show, :edit, :update, :destroy, :add_labour]

	def index
    @services = Service.all
	end

	def show
    @service_labour = ServiceLabour.new
    labours_of_services
	end

	def new
    @service = Service.new
	end

	def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: 'El servicio fue creado exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
	end

	def edit
	end

	def update
    if @service.update(service_params)
      redirect_to @service, notice: 'El servicio fue actualizado exitosamente.'
    else
      render :edit
    end
	end

	def destroy
    @service.destroy
    redirect_to services_path, notice: 'El servicio fue eliminado exitosamente.'
	end

	def add_labour
    @service_labour = ServiceLabour.new(service_labour_params)

    if @service_labour.save
      redirect_to service_path(@service.id), notice: 'Se agregó la labor correctamente.'
    else
			labours_of_services
      render :show, status: :unprocessable_entity
    end
	end

	def delete_labour
    @service_labour = ServiceLabour.find(params[:id])
    service_id = @service_labour.service_id
    @service_labour.destroy
    redirect_to service_path(service_id), notice: 'Labor eliminada exitosamente.'
	end

	private
	def labours_of_services
    @labours = @service.service_labours
	end

	def set_service
    @service = Service.find(params[:id])
	end

	def service_params
		params.require(:service).permit(
			:client_id,
			:technician_id,
			:description,
			:initial_date,
			:end_date
		)
	end

	def service_labour_params
		params.require(:service_labour).permit(
			:service_id,
			:labour_id,
			:duration,
			:description
		)
	end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_add_labour.html.erb
<%= form_with(model: @service_labour, url: add_labour_service_path, method: :put) do |form| %>
  <% @service_labour.errors.full_messages.each do |message| %>
      <div class="alert alert-danger">
        <%= message %>
      </div>
  <% end %>

  <%= form.hidden_field :service_id, value: @service.id %>

  <div class="mb-3">
    <%= form.label :labour_id, 'Seleccionar Labor:', class: 'form-label' %> <br>
    <%= form.collection_select :labour_id, @service.technician.labours, :id, lambda { |labour| labour.title }, {prompt: 'Seleccione una labor'}, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= form.label :duration, 'Duración:', class: 'form-label' %>
    <%= form.number_field :duration, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, 'Descripción:', class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Agregar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/services/_form.html.erb
<div class="container"> 
  <%= render partial: 'shared/back_button', locals: { back_path: services_path, class_name: "btn btn-outline-warning" } %> 
 
  <div class="row justify-content-center">
    <div  class="col-md-6">
      <%= form_with(model: @service, local: true , class: 'needs-validation') do |form| %>
        <% @service.errors.full_messages.each do |message| %>
          <div class="alert alert-danger">
            <%= message %>
          </div>
        <% end %>
      
        <div class="mb-3">
          <%= form.label :client_id, 'Seleccionar Cliente', class: 'form-label' %> <br>
          <%= form.collection_select :client_id, Client.all, :id, :name, {prompt: 'Seleccione un cliente'}, class: "form-select" %>
        </div>
      
        <div class="mb-3">
          <%= form.label :technician_id, 'Seleccionar Técnico', class: 'form-label' %>
          <%= form.collection_select :technician_id, Technician.all, :id, :name, {prompt: 'Seleccione un técnico'}, class: "form-select" %>
        </div>
      
        <div class="mb-3">
          <%= form.label :description, 'Descripción' %>
          <%= form.text_area :description, class: "form-control" %>
        </div>
      
        <div class="mb-3">
          <%= form.label :initial_date, 'Fecha de Inicio' %>
          <%= form.datetime_field :initial_date, class: "form-control" %>
        </div>
      
        <div class="mb-3">
          <%= form.submit 'Guardar', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/services/_labour.html.erb
<div class="container">
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Titulo</th>
          <th>Duracion en Horas</th>
          <th>Descripcion</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @labours.each do |labour| %>
          <tr>
              <td><%= labour.labour.title %></td>
              <td><%= labour.duration %></td>
              <td><%= labour.description %></td>
              <td><div><%= link_to 'Eliminar', delete_labour_service_path(labour.id), data: {
                      turbo_method: :delete,
                      turbo_confirm: '¿Estás seguro?'
                    }, class: "btn btn-danger me-2"
              %></div></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/services/edit.html.erb
<h2 class="text-center mb-4">Editar servicio</h2>

<%= render partial: 'form', service: @service %>

app/views/services/index.html.erb
<div class="container">
  <h1 class="text-center mb-4">Lista de Servicios</h1>
  <%= render partial: 'shared/back_button', locals: { back_path: root_path, class_name: "btn btn-outline-dark" } %>
  <%= link_to 'Nuevo servicio', new_service_path, class: 'btn btn-primary mb-3'%>

  <div class="table-responsive">
    <table class="table table-dordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Id</th>
          <th>cliente</th>
          <th>Tecnico</th>
          <th>Fecha de inicio</th>
          <th>Fecha final</th>
          <th>Descripcion</th>
        </tr>
      </thead>
      <tbody>
        <% @services.each do |service| %>
          <tr>
            <td><%= service.id %></td>
            <td>
              <%= link_to service_path(service.id), class: 'btn btn-info mb-3' do %>
                  <%= service.client.name %>
              <% end %>
            </td>
            <td><%= service.technician.name %></td>
            <td><%= service.initial_date %></td>
            <td><%= service.end_date %></td>
            <td><%= service.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/services/new.html.erb
<h2 class="text-center mb-4">Nueva servicio</h2>

<%= render partial: 'form', service: @service %>

app/views/services/show.html.erb
<div class="container">
  <%= render partial: 'shared/back_button', locals: { back_path: services_path, class_name: "btn btn-outline-dark" } %> 
  <h2 class="text-center mb-4"> Sericio #<%=@service.id%></h2>

  <div class="table-responsive">
    <table class="table table-dordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Id</th>
          <th>cliente</th>
          <th>Tecnico</th>
          <th>Fecha de inicio</th>
          <th>Fecha final</th>
          <th>Descripcion</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @service.id %></td>
            <td><%= @service.client.name %></td>
            <td><%= @service.technician.name %></td>
            <td><%= @service.initial_date %></td>
            <td><%= @service.end_date %></td>
            <td><%= @service.description %></td>
            <td>
              <div>
                <%= link_to 'Editar', edit_service_path(@service.id), class: "btn btn-primary me-2" %>
                <%= link_to 'Eliminar', service_path(@service.id), data: {
                  turbo_method: :delete,
                  turbo_confirm: '¿Estás seguro?'
                }, class: "btn btn-danger me-2" %>
              </div>
            </td>
          </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="container">
  <h2 class="text-center mb-4">Lista De Labores</h2>
  <%= render partial: 'labour'%>
</div>

<h2 class="text-center mb-4">Agregar labor</h2>
<div class="row mt-3 justify-content-center">
  <div class="col-md-6">
    <%= render partial: 'add_labour'%>
  </div>
</div>