config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root "main#home"

  resources :categories, only: [:index, :show]
  resources :labours, except: :show
  resources :areas, only: :index
  resources :skills

  resources :clients do
    put :assign_user, on: :member
  end

  resources :users

  resources :technicians do
    put :add_skill, on: :member
    delete :delete_skill, on: :member

    put :add_labour, on: :member
    delete :delete_labour, on: :member
  end

  resources :services do
      put :add_labour, on: :member
      delete :delete_labour, on: :member
  end
end

app/models/labour.rb
# == Schema Information
#
# Table name: labours
#
#  id         :integer          not null, primary key
#  title      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  skill_id   :integer          not null
#
# Indexes
#
#  index_labours_on_skill_id  (skill_id)
#
# Foreign Keys
#
#  skill_id  (skill_id => skills.id)
#
class Labour < ApplicationRecord
  belongs_to :skill

  validates_presence_of :title

  scope :root_labour, -> (skill_id) { joins(:skill).where(skill_id: skill_id).or(where(skill: {parent_id: skill_id})) }

  scope :by_skills, -> (skill_ids) { where(skill_id: skill_ids) }

end

app/controllers/labours_controller.rb
class LaboursController < ApplicationController
  before_action :find_labour, only: [:edit, :destroy, :update]

  def index
    if params[:skill_id].present?
      @labours = Labour.root_labour(params[:skill_id])
    else
      @labours = Labour.all
    end
  end

  def new
    @labour = Labour.new
  end

  def create
    @labour = Labour.new(labour_params)

    if @labour.save
      redirect_to labours_path, notice: 'Labor creada con éxito.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @labour.update(labour_params)
      redirect_to labours_path notice: 'Labor actualizada con éxito.'
    else
      render :edit
    end
  end

  def destroy
    @labour.destroy
    redirect_to labours_path, alert: 'Labor eliminada con éxito.'
  end

  private

  def find_labour
    @labour = Labour.find(params[:id])
  end

  def labour_params
    params.require(:labour).permit(:skill_id,:title)
  end
end

app/views/labours/_form.html.erb
<div class="container">
  <%= render partial: 'shared/back_button', locals: { back_path: labours_path, class_name: "btn btn-outline-warning" } %> 
  
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @labour) do |form| %>
        <% @labour.errors.full_messages.each do |message| %>
          <div class="alert alert-danger">
            <%= message %>
          </div>
        <% end %>
      
        <div class="mb-3 form-group">
          <%= form.label :skill_id, 'Seleccionar Categoría:' %>
          <%= form.collection_select :skill_id, Skill.subskills, :id, :name, { prompt: 'Selecciona una categoría' }, class: 'form-select' %>
        </div>
      
        <div class="mb-3 form-group">
          <%= form.label :title, 'Titulo' %>
          <%= form.text_area :title, class: 'form-control' %>
        </div>
      
        <div class="mb-3 form-group">
          <%= form.submit 'Guardar', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/labours/edit.html.erb
<h2 class="text-center mb-4">Editar Labor</h2>

<%= render partial: 'form', category_id: @category_id %>

app/views/labours/index.html.erb
<div class="container">
  <h1 class="text-center mb-4">Lista De labores</h1>
  <%= render partial: 'shared/back_button', locals: { back_path: root_path, class_name: "btn btn-outline-dark" } %>
  <%= link_to 'Nueva labor', new_labour_path, class: 'btn btn-primary' %>

  <div class="row justify-content-center mt-3">
    <div class="col-md-6">
      <%= form_tag labours_path, method: :get, id: 'filter-form', class: 'mb-3' do %>
        <%= label_tag :skill_id, 'Filtrar por categoría:', class: 'form-label' %>
        <%= select_tag :skill_id, options_for_select(Skill.subskills.sort_by_parent_name.map { |c| ["#{c.parent.name} - #{c.name}", c.id] }, params[:skill_id]), prompt: 'Todas las labores', class: 'form-select', onchange: 'submitFilterForm()' %>
        <%= submit_tag 'Filtrar', class: 'btn btn-primary', style: 'display: none;' %>
      <% end %>
    </div>
  </div>
</div>

<script>
  function submitFilterForm() {
    document.getElementById('filter-form').submit();
  }
</script>

<div class="container">
  <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th>Titulo</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @labours.each do |labour| %>
            <tr>
              <td><%= labour.title %></td>
              <td>
                <%= link_to 'Editar', edit_labour_path(labour), class: "btn btn-primary me-2" %>
                <%= link_to 'Eliminar', labour_path(labour), data: {
                  turbo_method: :delete,
                  turbo_confirm: '¿Estás seguro?'
                  }, class: "btn btn-danger me-2"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/labours/new.html.erb
<h2 class="text-center mb-4">Nueva Labor</h2>

<%= render partial: 'form', labour: @labour %>