config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root "main#home"

  resources :categories, only: [:index, :show]
  resources :labours, except: :show
  resources :areas, only: :index
  resources :skills

  resources :clients do
    put :assign_user, on: :member
  end

  resources :users

  resources :technicians do
    put :add_skill, on: :member
    delete :delete_skill, on: :member

    put :add_labour, on: :member
    delete :delete_labour, on: :member
  end

  resources :services do
      put :add_labour, on: :member
      delete :delete_labour, on: :member
  end
end

app/models/technician.rb
# == Schema Information
#
# Table name: technicians
#
#  id           :integer          not null, primary key
#  discarded_at :datetime
#  email        :text
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#
# Indexes
#
#  index_technicians_on_discarded_at  (discarded_at)
#
class Technician < ApplicationRecord
    include Discard::Model

    belongs_to :user, optional: true
    has_many :technician_skills, dependent: :destroy
    has_many :skills, through: :technician_skills

    has_many :technician_labours, dependent: :destroy
    has_many :labours, through: :technician_labours

    validates :name,:email, presence: true
    validates :user_id, uniqueness: true, allow_nil: true

end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :find_technician, only: [:show, :edit, :update, :destroy, :add_skill, :add_labour]

  def index
    @technicians = Technician.all
  end

  def show
    @technician_skill = TechnicianSkill.new
    @technician_labour = TechnicianLabour.new
    labours_and_skills_of_technician
  end

  def new
    @technician = Technician.new
  end

  def create
    @technician = Technician.new(technician_params)

    if @technician.save
      redirect_to technicians_path, notice: 'Técnico creado con éxito.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @technician.update(technician_params)
      redirect_to technicians_path, notice: 'Técnico actualizado con éxito.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @technician.discard
    redirect_to technicians_path, alert: 'Técnico eliminado con éxito.'
  end

  def add_skill
    @technician_skill = TechnicianSkill.new(add_skill_params)

    if @technician_skill.save
      redirect_to technician_path(@technician_skill.technician_id), notice: 'Habilidad agregada correctamente.'
    else
      @technician_labour = TechnicianLabour.new
      labours_and_skills_of_technician
      render :show, status: :unprocessable_entity
    end
  end

  def add_labour
    @technician_labour = TechnicianLabour.new(technician_id: @technician.id, labour_id: params[:labour_id], duration: params[:duration], price: params[:price])
    if @technician_labour.save
      redirect_to technician_path(@technician_labour.technician_id), notice: 'Labor agregada correctamente.'
    else
      @technician_skill = TechnicianSkill.new
      labours_and_skills_of_technician
      render :show, status: :unprocessable_entity
    end
  end

  def delete_skill
    @technician_skill = TechnicianSkill.find(params[:id])
    technician_id = @technician_skill.technician_id
    @technician_skill.destroy
    redirect_to technician_path(technician_id), alert: 'Habilidad eliminada exitosamente.'
  end

  def delete_labour
    @technician_labour = TechnicianLabour.find(params[:id])
    technician_id = @technician_labour.technician_id
    @technician_labour.destroy
    redirect_to technician_path(technician_id), alert: 'Labor eliminada exitosamente.'
  end

  private

  def labours_and_skills_of_technician
    @labours = @technician.technician_labours
    @skills = @technician.technician_skills
  end

  def find_technician
    @technician = Technician.find(params[:id])
  end

  def add_skill_params
    params.require(:technician_skill).permit(:skill_id, :level).merge(technician_id: @technician.id)
  end

  def technician_params
    params.require(:technician).permit(:name, :email)
  end
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/technicians/_add_labour.html.erb
<%= form_with(url: add_labour_technician_path, method: :put, class: 'needs-validation') do |form| %>
  <% if @technician_labour.present? %>
    <% @technician_labour.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
    <% end %>
  <% end %>

  <%= form.hidden_field :id, value: @technician.id %>

  <div class="mb-3">
    <%= form.label :labour_id, 'Seleccionar labor:', class: 'form-label' %>
    <%= form.collection_select :labour_id, Labour.by_skills(@technician.skills.pluck(:id)), :id, :title, { prompt: 'Selecciona una labor' }, { class: 'form-select' } %>
  </div>

  <div class="mb-3">
    <%= form.label :duration, 'Duración en Horas:', class: 'form-label' %>
    <%= form.number_field :duration, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :price, 'Price:', class: 'form-label' %>
    <%= form.number_field :price, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Agregar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/technicians/_add_skill.html.erb
<%= form_with(model: @technician_skill, url: add_skill_technician_path, method: :put, class: 'needs-validation') do |form| %>
  <% @technician_skill.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
      <%= message %>
    </div>
  <% end %>

  <%= form.hidden_field :id, value: @technician.id %>

  <div class="mb-3">
    <%= form.label :skill_id, 'Seleccionar Habilidad:', class: 'form-label' %> <br>
    <%= form.collection_select :skill_id, Skill.subskills, :id, :name, { prompt: 'Selecciona una Habilidad' }, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= form.label :level, 'Nivel:', class: 'form-label' %>
    <%= form.range_field :level, min: 1, max: 10, class: 'form-range' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Agregar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/technicians/_form.html.erb
<div class="container">
  <%= render partial: 'shared/back_button', locals: { back_path: technicians_path, class_name: "btn btn-outline-warning" } %> 

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with(model: @technician, local: true) do |form| %>
        <% @technician.errors.full_messages.each do |message| %>
          <div class="alert alert-danger">
            <%= message %>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.submit "Guardar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/technicians/edit.html.erb
<h2 class="text-center mb-4">Editar Tecnico.</h2>

<%= render 'form', technician: @technician %>

app/views/technicians/index.html.erb
<div class="container">
  <h1 class="text-center mb-4">Lista de Técnicos.</h1>
  <%= render partial: 'shared/back_button', locals: { back_path: root_path, class_name: "btn btn-outline-dark" } %>
  <%= link_to 'Nuevo Técnico', new_technician_path, class: 'btn btn-primary' %>

  <div class="table-responsive mt-3">
    <table class="table table-bordered table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Email</th>
          <th>Habilidades</th>
          <th>Level</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @technicians.each do |technician| %>
          <tr>
            <td>
              <%= technician.id %>
            </td>
            <td>
              <%= link_to technician.name, technician_path(technician), class:'btn btn-info mb-3'%>
            </td>
            <td>
              <%= technician.email %>
            </td>
            <td>
              <ul>
                <% technician.technician_skills.each do |technician_skill| %>
                  <li><%= technician_skill.skill.name %></li>
                <% end %>
              </ul>
            </td>
            <td>
              <ul>
                <% technician.technician_skills.each do |technician_skill| %>
                  <li><%= technician_skill.level %></li>
                <% end %>
              </ul>
            </td>
            <td>
              <%= link_to 'Editar', edit_technician_path(technician), class: "btn btn-primary me-2" %>
              <%= link_to technician.discarded? ? 'Recover' : 'Eliminar', technician_path(technician), data: {
                turbo_method: :delete,
                turbo_confirm: '¿Estás seguro?'
                }, class: "btn btn-danger me-2" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/technicians/new.html.erb
<h1 class="text-center mb-4">Nuevo Tecnico.</h1>

<%= render 'form' %>

app/views/technicians/show.html.erb
<div class="container">
  <%= render partial: 'shared/back_button', locals: { back_path: technicians_path, class_name: "btn btn-outline-dark" } %>
  <h4 class="justify-content-center"><%= "Técnico #{@technician.name}" %></h4>

  <div class="row mt-3">
    <div class="col-md-6">
      <h3>Habilidades:</h3>
      <table class="table table-dordered table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th scope="col">Habilidad</th>
            <th scope="col">Nivel</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @skills.each do |skill| %>
            <tr>
              <td><%= skill.skill.name %></td>
              <td>
                <div class="progress">
                  <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar" style="width: <%= skill.level * 10 %>%" aria-valuenow="<%= skill.level * 10 %>" aria-valuemin="0" aria-valuemax="100"><%= skill.level %></div>
                </div>
              </td>
              <td>
                <%= link_to 'Eliminar', delete_skill_technician_path(skill.id), data: {
                  turbo_method: :delete,
                  turbo_confirm: '¿Estás seguro?'
                  }, class: 'btn btn-danger'
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <h3>Labores:</h3>
      <table class="table table-dordered table-striped table-hover">
        <thead class="table-dark">
          <tr>
            <th scope="col">Titulo</th>
            <th scope="col">Duracion En Horas</th>
            <th scope="col">Price</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @labours.each do |labour| %>
            <tr>
              <td><%= labour.labour.title %></td>
              <td><%= labour.duration %></td>
              <td><%= "$#{labour.price}" %></td>
              <td>
                <%= link_to 'Eliminar', delete_labour_technician_path(labour.id), data: {
                  turbo_method: :delete,
                  turbo_confirm: '¿Estás seguro?'
                  }, class: 'btn btn-danger'
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <div class="container row justify-content-center">
        <h3 class="row justify-content-center">Agregar Habilidad</h3>
          <div class="col-md-6">
            <%= render partial: 'add_skill' %>
          </div>
      </div>

      <div class="container row justify-content-center">
        <h3 class="row justify-content-center">Agregar Labor</h3>
          <div class="col-md-6">
            <%= render partial: 'add_labour' %>
          </div>
      </div>
    </div>
  </div>
</div>